on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]

jobs:
  create-asana-attachment-job:
    runs-on: ubuntu-latest
    name: Post an attachment
    steps:
      - name: Post an attachment
        uses: https://github.com/whitershade/create-app-attachment-github-action@v1.2
        id: postAttachment
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}
      - name: Get status
        run: echo "Status is ${{ steps.postAttachment.outputs.status }}"
